[build]
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/downloader/*"
  to = "/.netlify/functions/downloader/:splat"
  status = 200

[[redirects]]
  from = "/api/stalk/*"
  to = "/.netlify/functions/stalk/:splat"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
