[build]
  publish = "public"  
  functions = "netlify/functions"  !

# DOWNLOADER API
[[redirects]]
  from = "/api/downloader/tiktok"
  to = "/.netlify/functions/tiktok"
  status = 200

[[redirects]]
  from = "/api/downloader/youtube"
  to = "/.netlify/functions/youtube"
  status = 200

[[redirects]]
  from = "/api/downloader/instagram"
  to = "/.netlify/functions/instagram"
  status = 200

[[redirects]]
  from = "/api/downloader/twitter"
  to = "/.netlify/functions/twitter"
  status = 200

[[redirects]]
  from = "/api/downloader/pinterest"
  to = "/.netlify/functions/pinterest"
  status = 200

[[redirects]]
  from = "/api/downloader/facebook"
  to = "/.netlify/functions/facebook"
  status = 200

# STALKER API
[[redirects]]
  from = "/api/stalker/wuwastalker"
  to = "/.netlify/functions/wuwastalker"
  status = 200

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"


